trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'
  registry: 'eeba19/cicd-frontend'
  dockerImage: ''
  DOCKER_USERNAME: $(DOCKER_USERNAME)
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

jobs:
- job: build_and_deploy
  displayName: 'Build and Deploy'
  timeoutInMinutes: 30  # Erhöhter Timeout für längere Pipeline

  steps:
    - checkout: self
      displayName: 'Checkout repository'

    - script: |
        echo 'Running SonarQube analysis...'
        scannerHome=$(which sonar-scanner)
        sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=. -Dsonar.host.url=http://your-sonarqube-server -Dsonar.login=$(SONARQUBE_TOKEN)
      displayName: 'Linting'
      env:
        SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

    - script: |
        echo 'Running tests...'
        # Hier können deine Testbefehle eingefügt werden
      displayName: 'Testing'

    - script: |
        echo 'Building Docker image...'
        dockerImage=$(docker build -t $(registry) .)
        echo "##vso[task.setvariable variable=dockerImage]$dockerImage"
      displayName: 'Build Docker Image'

    - script: |
        echo 'Logging in to Docker Hub...'
        echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin https://registry.hub.docker.com
        echo 'Tagging and pushing Docker image...'
        docker tag $(dockerImage) $(registry):$(Build.BuildId)
        docker tag $(dockerImage) $(registry):latest
        docker push $(registry):$(Build.BuildId)
        docker push $(registry):latest
      displayName: 'Push Docker Image to Docker Hub'
      env:
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

    - script: |
        echo 'Deploying app...'
        # Hier können deine Bereitstellungsbefehle eingefügt werden
      displayName: 'Deploy App'
