trigger:
  branches:
    include:
      - main  # Trigger on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'
  DOCKER_REGISTRY: 'docker.io'
  DOCKER_IMAGE_NAME: 'eeba19/cicd-frontend'

jobs:
- job: build-and-deploy
  displayName: 'Build and Deploy'
  steps:
    - task: Checkout@2
      displayName: 'Checkout repository'

    - task: UseNode@1
      displayName: 'Set up Node.js'
      inputs:
        version: '16.x'  # Adjust Node.js version as needed

    - script: |
        npm ci --legacy-peer-deps  # Use npm ci for clean installs
      displayName: 'Install dependencies'

    - script: |
        npx eslint --config ./eslint.config.js
      displayName: 'Linting'

    - script: |
        echo 'Running tests...'  # Replace with your test command
      displayName: 'Testing'

    - script: |
        docker build -t $(DOCKER_IMAGE_NAME) .
      displayName: 'Build Docker Image'

    - script: |
        echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
        docker tag $(DOCKER_IMAGE_NAME) $(DOCKER_REGISTRY)/$(DOCKER_IMAGE_NAME)
        docker push $(DOCKER_REGISTRY)/$(DOCKER_IMAGE_NAME)
      displayName: 'Push Docker Image to Docker Hub'

    - script: |
        echo 'Deploying app...'  # Replace with your deployment commands
      displayName: 'Deploy App'
