trigger:
  branches:
    include:
      - main  # Trigger on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_ENV: 'production'
  registry: 'eeba19/cicd-frontend'
  dockerImage: ''
  # Reference the variable group for Docker and SonarQube credentials
  DOCKER_USERNAME: $(DOCKER_USERNAME)
  DOCKER_PASSWORD: $(DOCKER_PASSWORD)
  SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)

jobs:
- job: build_and_deploy
  displayName: 'Build and Deploy'
  timeoutInMinutes: 5
  steps:
    - checkout: self
      displayName: 'Checkout repository'

    - script: |
        echo 'Running SonarQube analysis...'
        scannerHome=$(which sonar-scanner)
        sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=. -Dsonar.host.url=http://your-sonarqube-server -Dsonar.login=$(SONARQUBE_TOKEN)
      displayName: 'Linting'
      env:
        SONARQUBE_TOKEN: $(SONARQUBE_TOKEN)  # Add SonarQube token to the Azure DevOps pipeline variables

    - script: |
        echo 'A/B Testing Stage'
      displayName: 'Testing'

    - script: |
        dockerImage=$(docker build -t $(registry) .)
        echo "##vso[task.setvariable variable=dockerImage]$dockerImage"
      displayName: 'Build Docker Image'

    - script: |
        echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin https://registry.hub.docker.com
        docker tag $(dockerImage) $(registry):$(Build.BuildId)
        docker tag $(dockerImage) $(registry):latest
        docker push $(registry):$(Build.BuildId)
        docker push $(registry):latest
      displayName: 'Push Docker Image to Docker Hub'
      env:
        DOCKER_USERNAME: $(DOCKER_USERNAME)
        DOCKER_PASSWORD: $(DOCKER_PASSWORD)

    - script: |
        echo 'Deploying app...'
      displayName: 'Deploy App'
