name: CI/CD Pipeline for Vue.js Project

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ./cicd-frontend-main
        run: npm install --legacy-peer-deps

      - name: Set executable permissions for ESLint (if needed)
        run: chmod +x ./node_modules/.bin/eslint

      - name: Run ESLint
        working-directory: ./cicd-frontend-main
        run: npx eslint 'src/**/*.{js,vue}'

  test:
    name: Testing
    needs: lint  # Run tests only after linting succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: ./cicd-frontend-main
        run: npm install --legacy-peer-deps

      - name: Run tests
        working-directory: ./cicd-frontend-main
        run: npm run test
