name: CI/CD Pipeline für Vue.js Projekt

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: Linten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Repository-Code auschecken

      - name: Node.js 16 verwenden
        uses: actions/setup-node@v3
        with:
          node-version: 16.x  # Anpassen, falls nötig für dein Projekt

      - name: Abhängigkeiten installieren
        working-directory: ./cicd-frontend-main
        run: npm install --legacy-peer-deps

      - name: Ausführbare Berechtigungen setzen
        working-directory: ./cicd-frontend-main
        run: chmod +x ./node_modules/.bin/eslint

      - name: ESLint ausführen
        working-directory: ./cicd-frontend-main
        run: npx eslint 'src/**/*.{js,vue}'

  test:
    name: Testen
    needs: lint  # Tests nur ausführen, wenn das Linting erfolgreich war
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Node.js 16 verwenden
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Abhängigkeiten installieren
        working-directory: ./cicd-frontend-main
        run: npm install --legacy-peer-deps

      - name: Tests ausführen
        working-directory: ./cicd-frontend-main
        run: npm run test
